export CXX=mpic++

DEFAULT = -std=c++20 
DEBUG = -g -Wall -DDEBUG -std=c++20 -pedantic  
OPTIM =-O3 -std=c++20 

SETTINGS ?= OPTIM

ifeq ($(SETTINGS), DEFAULT)
	CXXFLAGS = $(DEFAULT)
else ifeq ($(SETTINGS), DEBUG)
	CXXFLAGS =  $(DEBUG)
else ifeq ($(SETTINGS), OPTIM)
	CXXFLAGS =  $(OPTIM)
endif

MAKE = make SETTINGS="$(SETTINGS)"

# Flags
LDFLAGS := -L$(H5LD) -lhdf5 -lhdf5_cpp -L$(MPICHLD)

