CXX=g++

SETTINGS = DEBUG

DEFAULT= -std=c++20 
DEBUG= -g -Wall -DDEBUG -std=c++20 -pedantic  
OPTIM=-O3 -std=c++20 


ifeq ($(SETTINGS), DEFAULT)
	CPPFLAGS = $(DEFAULT)
else ifeq ($(SETTINGS), DEBUG)
	CPPFLAGS =  $(DEBUG)
else ifeq ($(SETTINGS), OPTIM)
	CPPFLAGS =  $(OPTIM)
endif

MAKE = make SETTINGS="$(SETTINGS)"
